-- ============================================================================
-- NEIGHBOURLY ORACLE MIGRATION: 01_TABLES
-- ============================================================================
-- REQUIREMENT: Oracle 23ai (for native BOOLEAN/JSON support)
-- EXECUTION: Run scripts 01-05 in sequence.
-- ROLLBACK: If any step fails, run 'oracle_99_rollback.sql'.
-- ============================================================================

CREATE TABLE users (
    id RAW(16) DEFAULT SYS_GUID() PRIMARY KEY,
    email VARCHAR2(255) NOT NULL UNIQUE,
    password_hash VARCHAR2(255) NOT NULL,
    phone VARCHAR2(20) UNIQUE,
    role VARCHAR2(20) DEFAULT 'seeker' NOT NULL,
    status VARCHAR2(30) DEFAULT 'pending_verification' NOT NULL,
    email_verified BOOLEAN DEFAULT FALSE,
    phone_verified BOOLEAN DEFAULT FALSE,
    last_login_at TIMESTAMP WITH TIME ZONE,
    failed_login_attempts NUMBER DEFAULT 0,
    locked_until TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP WITH TIME ZONE,
    
    CONSTRAINT user_role_check CHECK (role IN ('seeker', 'provider', 'moderator', 'admin')),
    CONSTRAINT user_status_check CHECK (status IN ('active', 'suspended', 'deactivated', 'pending_verification')),
    CONSTRAINT email_format CHECK (REGEXP_LIKE(email, '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$')),
    CONSTRAINT phone_format CHECK (phone IS NULL OR REGEXP_LIKE(phone, '^\+?[1-9]\d{1,14}$'))
);

CREATE TABLE user_profiles (
    user_id RAW(16) PRIMARY KEY,
    first_name VARCHAR2(100) NOT NULL,
    last_name VARCHAR2(100) NOT NULL,
    display_name VARCHAR2(150),
    avatar_url VARCHAR2(500),
    bio CLOB,
    date_of_birth DATE,
    verification_status VARCHAR2(20) DEFAULT 'unverified',
    verification_document_url VARCHAR2(500),
    verified_at TIMESTAMP WITH TIME ZONE,
    verified_by RAW(16),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    
    CONSTRAINT profile_v_status_check CHECK (verification_status IN ('unverified', 'pending', 'verified', 'rejected')),
    CONSTRAINT age_requirement CHECK (date_of_birth IS NULL OR date_of_birth <= ADD_MONTHS(CURRENT_DATE, -12*18))
);

CREATE TABLE user_reputation (
    user_id RAW(16) PRIMARY KEY,
    total_reviews NUMBER DEFAULT 0,
    average_rating NUMBER(3, 2) DEFAULT 0.00,
    total_bookings_as_provider NUMBER DEFAULT 0,
    -- total_bookings_as_seeker NUMBER DEFAULT 0,
    completed_bookings_as_provider NUMBER DEFAULT 0,
    -- completed_bookings_as_seeker NUMBER DEFAULT 0,
    cancellation_rate NUMBER(5, 2) DEFAULT 0.00,
    response_time_minutes NUMBER,
    reliability_score NUMBER(5, 2) DEFAULT 0.00,
    last_active_at TIMESTAMP WITH TIME ZONE,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    
    CONSTRAINT valid_avg_rating CHECK (average_rating BETWEEN 0 AND 5),
    CONSTRAINT valid_cancel_rate CHECK (cancellation_rate BETWEEN 0 AND 100)
);

-- ============================================================================
-- 2. GEOGRAPHY DOMAIN
-- ============================================================================

CREATE TABLE cities (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100) NOT NULL,
    state_province VARCHAR2(100),
    country VARCHAR2(100) NOT NULL,
    country_code CHAR(2) NOT NULL,
    timezone VARCHAR2(50) NOT NULL,
    -- is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    
    CONSTRAINT unique_city UNIQUE (name, state_province, country)
);

CREATE TABLE neighborhoods (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    city_id NUMBER NOT NULL,
    name VARCHAR2(150) NOT NULL,
    slug VARCHAR2(150),
    description CLOB,
    h3_resolution NUMBER DEFAULT 10,
    h3_cells JSON,
    boundary_geojson JSON,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    
    CONSTRAINT unique_neighborhood UNIQUE (city_id, name)
);

CREATE TABLE addresses (
    id RAW(16) DEFAULT SYS_GUID() PRIMARY KEY,
    user_id RAW(16),
    street_address VARCHAR2(255) NOT NULL,
    apartment VARCHAR2(50),
    city_id NUMBER NOT NULL,
    neighborhood_id NUMBER,
    postal_code VARCHAR2(20) NOT NULL,
    latitude NUMBER(10, 8) NOT NULL,
    longitude NUMBER(11, 8) NOT NULL,
    h3_index VARCHAR2(20) NOT NULL,
    h3_resolution NUMBER DEFAULT 9,
    is_primary BOOLEAN DEFAULT FALSE,
    is_verified BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    
    CONSTRAINT valid_coords CHECK (latitude BETWEEN -90 AND 90 AND longitude BETWEEN -180 AND 180)
);

-- ============================================================================
-- 3. SERVICE DOMAIN
-- ============================================================================

CREATE TABLE service_categories (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_id NUMBER,
    name VARCHAR2(100) NOT NULL,
    slug VARCHAR2(100) UNIQUE NOT NULL,
    description CLOB,
    icon_url VARCHAR2(500),
    is_active BOOLEAN DEFAULT TRUE,
    sort_order NUMBER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    
    CONSTRAINT no_self_ref_cat CHECK (id != parent_id)
);

CREATE TABLE service_listings (
    id RAW(16) DEFAULT SYS_GUID() PRIMARY KEY,
    provider_id RAW(16) NOT NULL,
    category_id NUMBER NOT NULL,
    title VARCHAR2(200) NOT NULL,
    slug VARCHAR2(250) UNIQUE NOT NULL,
    description CLOB NOT NULL,
    short_description VARCHAR2(500),
    price_amount NUMBER(10, 2) NOT NULL,
    price_currency CHAR(3) DEFAULT 'USD',
    price_unit VARCHAR2(50) DEFAULT 'per_hour',
    address_id RAW(16),
    h3_index VARCHAR2(20),
    service_radius_km NUMBER DEFAULT 5,
    duration_minutes NUMBER,
    images JSON DEFAULT '[]',
    tags JSON,
    status VARCHAR2(20) DEFAULT 'draft',
    is_featured BOOLEAN DEFAULT FALSE,
    view_count NUMBER DEFAULT 0,
    booking_count NUMBER DEFAULT 0,
    published_at TIMESTAMP WITH TIME ZONE,
    expires_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP WITH TIME ZONE,
    
    CONSTRAINT srv_status_check CHECK (status IN ('draft', 'active', 'paused', 'completed', 'archived')),
    CONSTRAINT pos_price CHECK (price_amount >= 0),
    CONSTRAINT pos_duration CHECK (duration_minutes IS NULL OR duration_minutes > 0),
    CONSTRAINT valid_radius CHECK (service_radius_km BETWEEN 1 AND 100)
);

CREATE TABLE service_availability (
    id RAW(16) DEFAULT SYS_GUID() PRIMARY KEY,
    service_id RAW(16) NOT NULL,
    day_of_week NUMBER NOT NULL,
    start_time INTERVAL DAY TO SECOND NOT NULL,
    end_time INTERVAL DAY TO SECOND NOT NULL,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    
    CONSTRAINT valid_day CHECK (day_of_week BETWEEN 0 AND 6),
    CONSTRAINT valid_time_range CHECK (end_time > start_time),
    CONSTRAINT unique_availability UNIQUE (service_id, day_of_week, start_time)
);

-- ============================================================================
-- 4. BOOKINGS & TRANSACTIONS
-- ============================================================================

-- need to add another table with the cancellation details and link it to booking for normalization 
CREATE TABLE bookings (
    id RAW(16) DEFAULT SYS_GUID() PRIMARY KEY,
    service_id RAW(16) NOT NULL,
    seeker_id RAW(16) NOT NULL,
    provider_id RAW(16) NOT NULL,
    booking_reference VARCHAR2(20) UNIQUE NOT NULL,
    scheduled_start TIMESTAMP WITH TIME ZONE NOT NULL,
    scheduled_end TIMESTAMP WITH TIME ZONE NOT NULL,
    actual_start TIMESTAMP WITH TIME ZONE,
    actual_end TIMESTAMP WITH TIME ZONE,
    status VARCHAR2(20) DEFAULT 'pending',
    total_amount NUMBER(10, 2) NOT NULL,
    currency CHAR(3) DEFAULT 'USD',
    special_instructions CLOB,
    confirmed_at TIMESTAMP WITH TIME ZONE,
    completed_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    

    cancellation_reason CLOB,
    cancelled_by RAW(16),
    cancelled_at TIMESTAMP WITH TIME ZONE,
    
    CONSTRAINT booking_status_check CHECK (status IN ('pending', 'confirmed', 'in_progress', 'completed', 'cancelled', 'disputed')),
    CONSTRAINT no_self_book CHECK (seeker_id != provider_id),
    CONSTRAINT valid_sched CHECK (scheduled_end > scheduled_start),
    CONSTRAINT pos_amt CHECK (total_amount >= 0)
);

CREATE TABLE reviews (
    id RAW(16) DEFAULT SYS_GUID() PRIMARY KEY,
    booking_id RAW(16) NOT NULL UNIQUE,
    reviewer_id RAW(16) NOT NULL,
    reviewee_id RAW(16) NOT NULL,
    rating NUMBER NOT NULL,
    title VARCHAR2(150),
    comment_text CLOB,
    response CLOB,
    response_at TIMESTAMP WITH TIME ZONE,
    -- is_anonymous BOOLEAN DEFAULT FALSE,
    -- is_flagged BOOLEAN DEFAULT FALSE,
    -- flagged_reason CLOB,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    
    CONSTRAINT valid_rating_val CHECK (rating BETWEEN 1 AND 5),
    CONSTRAINT no_self_rev CHECK (reviewer_id != reviewee_id)
);

CREATE TABLE transactions (
    id RAW(16) DEFAULT SYS_GUID() PRIMARY KEY,
    booking_id RAW(16) NOT NULL,
    payer_id RAW(16) NOT NULL,
    payee_id RAW(16) NOT NULL,
    amount NUMBER(10, 2) NOT NULL,
    currency CHAR(3) DEFAULT 'USD',
    platform_fee NUMBER(10, 2) DEFAULT 0.00,
    net_amount NUMBER(10, 2) NOT NULL,
    status VARCHAR2(20) DEFAULT 'pending',
    payment_method VARCHAR2(50),
    payment_gateway_ref VARCHAR2(255),
    payment_gateway_response JSON,
    processed_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,

    refunded_at TIMESTAMP WITH TIME ZONE,
    refund_reason CLOB,
    
    CONSTRAINT tx_status_check CHECK (status IN ('pending', 'completed', 'failed', 'refunded')),
    CONSTRAINT pos_tx_amt CHECK (amount > 0),
    CONSTRAINT valid_net_amt CHECK (net_amount = amount - platform_fee)
);

CREATE TABLE disputes (
    id RAW(16) DEFAULT SYS_GUID() PRIMARY KEY,
    booking_id RAW(16) NOT NULL,
    raised_by RAW(16) NOT NULL,
    against_user_id RAW(16) NOT NULL,
    category VARCHAR2(100) NOT NULL,
    description CLOB NOT NULL,
    evidence JSON,
    status VARCHAR2(20) DEFAULT 'open',
    assigned_moderator_id RAW(16),
    resolution CLOB,
    resolved_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    
    CONSTRAINT dispute_status_check CHECK (status IN ('open', 'under_review', 'resolved', 'closed'))
);

-- ============================================================================
-- 5. PERMISSIONS & CACHE
-- ============================================================================

CREATE TABLE permissions (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100) UNIQUE NOT NULL,
    resource VARCHAR2(100) NOT NULL,
    action VARCHAR2(50) NOT NULL,
    description CLOB,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    
    CONSTRAINT unique_perm_act UNIQUE (resource, action)
);

CREATE TABLE role_permissions (
    role VARCHAR2(20) NOT NULL,
    permission_id NUMBER NOT NULL,
    granted_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    
    PRIMARY KEY (role, permission_id),
    CONSTRAINT role_type_check CHECK (role IN ('seeker', 'provider', 'moderator', 'admin'))
);

CREATE TABLE user_permission_overrides (
    id RAW(16) DEFAULT SYS_GUID() PRIMARY KEY,
    user_id RAW(16) NOT NULL,
    permission_id NUMBER NOT NULL,
    is_granted BOOLEAN NOT NULL,
    reason CLOB,
    granted_by RAW(16),
    granted_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    expires_at TIMESTAMP WITH TIME ZONE,
    
    CONSTRAINT unique_user_perm UNIQUE (user_id, permission_id)
);

CREATE TABLE trending_services_cache (
    neighborhood_id NUMBER NOT NULL,
    service_id RAW(16) NOT NULL,
    trend_score NUMBER(10, 2) NOT NULL,
    period VARCHAR2(20) NOT NULL,
    calculated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    
    PRIMARY KEY (neighborhood_id, service_id, period)
);
