CREATE OR REPLACE TRIGGER trg_users_upd
BEFORE UPDATE ON users FOR EACH ROW
BEGIN :NEW.updated_at := CURRENT_TIMESTAMP; END;
/

CREATE OR REPLACE TRIGGER trg_user_profiles_upd
BEFORE UPDATE ON user_profiles FOR EACH ROW
BEGIN :NEW.updated_at := CURRENT_TIMESTAMP; END;
/

CREATE OR REPLACE TRIGGER trg_neighborhoods_upd
BEFORE UPDATE ON neighborhoods FOR EACH ROW
BEGIN :NEW.updated_at := CURRENT_TIMESTAMP; END;
/

CREATE OR REPLACE TRIGGER trg_addresses_upd
BEFORE UPDATE ON addresses FOR EACH ROW
BEGIN :NEW.updated_at := CURRENT_TIMESTAMP; END;
/

CREATE OR REPLACE TRIGGER trg_service_listings_upd
BEFORE UPDATE ON service_listings FOR EACH ROW
BEGIN :NEW.updated_at := CURRENT_TIMESTAMP; END;
/

CREATE OR REPLACE TRIGGER trg_bookings_upd
BEFORE UPDATE ON bookings FOR EACH ROW
BEGIN :NEW.updated_at := CURRENT_TIMESTAMP; END;
/

CREATE OR REPLACE TRIGGER trg_reviews_upd
BEFORE UPDATE ON reviews FOR EACH ROW
BEGIN :NEW.updated_at := CURRENT_TIMESTAMP; END;
/

CREATE OR REPLACE TRIGGER trg_disputes_upd
BEFORE UPDATE ON disputes FOR EACH ROW
BEGIN :NEW.updated_at := CURRENT_TIMESTAMP; END;
/
